require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WritingsController do

  def mock_writing(stubs={})
    @mock_writing ||= mock_model(Writing, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all writings as @writings" do
      Writing.stub(:all) { [mock_writing] }
      get :index
      assigns(:writings).should eq([mock_writing])
    end
  end

  describe "GET show" do
    it "assigns the requested writing as @writing" do
      Writing.stub(:find).with("37") { mock_writing }
      get :show, :id => "37"
      assigns(:writing).should be(mock_writing)
    end
  end

  describe "GET new" do
    it "assigns a new writing as @writing" do
      Writing.stub(:new) { mock_writing }
      get :new
      assigns(:writing).should be(mock_writing)
    end
  end

  describe "GET edit" do
    it "assigns the requested writing as @writing" do
      Writing.stub(:find).with("37") { mock_writing }
      get :edit, :id => "37"
      assigns(:writing).should be(mock_writing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created writing as @writing" do
        Writing.stub(:new).with({'these' => 'params'}) { mock_writing(:save => true) }
        post :create, :writing => {'these' => 'params'}
        assigns(:writing).should be(mock_writing)
      end

      it "redirects to the created writing" do
        Writing.stub(:new) { mock_writing(:save => true) }
        post :create, :writing => {}
        response.should redirect_to(writing_url(mock_writing))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved writing as @writing" do
        Writing.stub(:new).with({'these' => 'params'}) { mock_writing(:save => false) }
        post :create, :writing => {'these' => 'params'}
        assigns(:writing).should be(mock_writing)
      end

      it "re-renders the 'new' template" do
        Writing.stub(:new) { mock_writing(:save => false) }
        post :create, :writing => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested writing" do
        Writing.stub(:find).with("37") { mock_writing }
        mock_writing.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :writing => {'these' => 'params'}
      end

      it "assigns the requested writing as @writing" do
        Writing.stub(:find) { mock_writing(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:writing).should be(mock_writing)
      end

      it "redirects to the writing" do
        Writing.stub(:find) { mock_writing(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(writing_url(mock_writing))
      end
    end

    describe "with invalid params" do
      it "assigns the writing as @writing" do
        Writing.stub(:find) { mock_writing(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:writing).should be(mock_writing)
      end

      it "re-renders the 'edit' template" do
        Writing.stub(:find) { mock_writing(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested writing" do
      Writing.stub(:find).with("37") { mock_writing }
      mock_writing.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the writings list" do
      Writing.stub(:find) { mock_writing }
      delete :destroy, :id => "1"
      response.should redirect_to(writings_url)
    end
  end

end
